### ISSUE TITLE
Why need a separate repo to store Cask.toml

### ISSUE THREAD

**Issue by iawia002** [axetroy/cask.rs#4]
I see the configuration is only one file, why not just put `Cask.toml` in the project repo instead of creating a separate one, I understand that `Cask.toml` should also be part of the project, no need to store it separately.

**Comment by axetroy** [comment]
I can understand that this may make people confused or have invasiveness.

Imagine what happens in the same directory in the same directory?

In order to fetch `Cask.toml` file, We have to clone the entire project, for some large projects, this seriously affects the speed

Or if you have any better suggestions, welcome

**Comment by iawia002** [comment]
> In order to fetch `Cask.toml` file, We have to clone the entire project, for some large projects, this seriously affects the speed

This could indeed lead to some problems.

I didn't think of a good solution, what do you think about us supporting both ways? Either in the project repo or in a separate repo, with preference given to trying to fetch it from the separate repo.

**Comment by axetroy** [comment]
> with preference given to trying to fetch it from the separate repo.

How about adding a new flag？

By default, it is still getting from a separate repo

But we can add a FLAG to get it from the current repo. 

```bash
cask install github.com/iawia002/lux --current
```

**Comment by iawia002** [comment]
Adding a flag will increase the cost of use, so we can just try the two URLs separately in our code: if we fetch the `{package}-cask` URL failed, try fetching the `{package}` URL again.

**Comment by axetroy** [comment]
> Adding a flag will increase the cost of use, so we can just try the two URLs separately in our code: if we fetch the `{package}-cask` URL failed, try fetching the `{package}` URL again.

LGTM

**Comment by iawia002** [comment]
If there is no rush I can implement this feature.

**Comment by axetroy** [comment]
> If there is no rush I can implement this feature.

Nice!

**Comment by axetroy** [comment]
> if we fetch the {package}-cask URL failed

Here is the method to how detect the repo exists or not #8
