### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by hahaha108** [axetroy/cask.rs#42]
PS C:\Users\Administrator\Desktop> cask install github.com/iawia002/lux
Fetching github.com/iawia002/lux formula...
thread 'main' panicked at 'install package fail!: can not found package github.com/iawia002/lux

Location:
    src\formula.rs:215:17', src/main.rs:210:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by axetroy** [comment]
感谢反馈。

我试了一遍，是可以的，这里有个关键，因为是从 Github 获取信息，所以一般情况下的网络，是访问不到的，这就会导致找不到这个包而安装失败

```bash
$ cask install github.com/iawia002/lux
Fetching github.com/iawia002/lux formula...
Downloading https://github.com/iawia002/lux/releases/download/v0.16.0/lux_0.16.0_macOS_64-bit.tar.gz
⠒ [00:02:50] [##########################################################>----------------------] 7.73MiB/10.68MiB (46.76KiB/s, 1m)
```

解决办法：
1. 改 HOST
2. 改 DNS
3. 科学上网
